### PR TITLE
Fixes #124: Include svg files in dist/css/img in npm package and move docs-specific images out of dist/css/img."

### LINKED ISSUE #124: Images missing from dist when installed via npm
### Describe the bug
Reported by @matt-e-king.  When installing Arizona Bootstrap via `npm install`, images referenced by the dist css files are not included in the dist directory.

### To Reproduce
Install arizona-bootstrap with npm (inside another project) following the directions in the documentation (https://digital.arizona.edu/arizona-bootstrap/docs/0.0/getting-started/download/#npm):
```
mkdir new-project
cd new-project
npm init
npm install https://github.com/az-digital/arizona-bootstrap
cd node_modules/arizona-bootstrap
ls dist
```

## Proposed resolution
Look into how to include the image files referenced by dist css in the dist directory

### Expected behavior
Any images referenced by dist css files should be part of dist

### PR DESCRIPTION
**Pull request by joeparsons**
Closes #124 

@matt-e-king Noticed that when Arizona Bootstrap is installed via npm per our documented instructions, the svg images that various Arizona Bootstrap styles depend on are not included in the copy of Arizona Bootstrap installed by npm.  This seems to be because the `files` property in our `package.json` was only whitelisting specific file patterns.  This should allow those svg files to be included.

I also noticed that we had some documentation-specific images (demo Photo Gallery images) living in `dist/css/img` that really belong in the documentation `assets` directory.

### CODE REVIEW

**Comment by joeparsons** [comment]
Verified photo gallery images are still working in the Photo Gallery component documentation in the PR review site:
https://review.digital.arizona.edu/arizona-bootstrap/issue/124/docs/2.0/components/photo-gallery/

**Comment by joeparsons** [comment]
Confirmed that the `dist/css/img/*.svg` files exist in `node_modules/arizona-bootstrap` after installing this branch locally via npm:

```
mkdir npm-test
cd npm-test
npm init
npm install https://github.com/az-digital/arizona-bootstrap#issue/124
```

**Comment by matt-e-king** [comment]
@joeparsons local testing worked for me as well.

There is another use case (maybe should be another GitHub issue) where a project might want to ingest only the `scss` from this npm package:

```
// background-wrapper.scss contains all the img references
@import "../../node_modules/arizona-bootstrap/scss/background-wrapper";
```

The `img` directory is not a sibiling to the `scss` files so a similar issue would occur.

I know this is only a use case as of recent conversations to use `arizona-bootstrap` as a `scss` dependency for the potential `arizona-frontend` libraries, so not sure if the responsibility should fall on this package. Either way, I'll wait for your response before approving this pull request.

**Comment by joeparsons** [comment]
@matt-e-king Thanks for reviewing!  I had also noticed that the svg images were currently _only_ in the `dist/css/img` directory and was actually just looking into what the best way to copy those images into `dist` as part of our our build tools toolchain would be (since, IMHO, all of the files in `dist` should be able to regenerated by our build process(es).  I do think it would probably be best to break this improvement into a separate issue / PR.  I can create an issue for that.

**Review by matt-e-king — APPROVED** [review]

**Review by trackleft — APPROVED** [review]
Beautiful!

**Comment by joeparsons** [comment]
Follow-up issue to address `.scss` problem described by @matt-e-king: #155

**Pull request merged**
