### PR TITLE
Closes #1197 - Make form labels visually distinguishable from description text

### LINKED ISSUE #1197: Make form labels visually distinguishable from description text
## Problem/Motivation
Originally from az-digital/az_quickstart#3249 , and is preferable to fix at the Bootstrap level than in the AZ Barrio Drupal theme. Form labels are not visually distinguishable from description text.

Label styling is currently the same as description text, making it visually indistinguishable and confusing for visual users filling out the forms.

## Proposed resolution
Increase font-size and boldness of non-checkbox/radio `<label>`s. Adapt the CSS used in AZ Barrio to fit in AZ Bootstrap context:
```
form.webform-submission-form {
  label:not(.form-check-label) {
    font-size: 18px;
    font-weight: 700;
  }
}

```

### Expected behavior
Form labels are visually distinguishable from description text.

### PR DESCRIPTION
**Pull request by akslay**
Makes form labels visually distinguishable from description text by increasing their size and boldness. Checkbox/radio labels are excluded from this change.

Originally stemmed from https://github.com/az-digital/az_quickstart/pull/3249
Closes #1197 

Review link: https://review.digital.arizona.edu/arizona-bootstrap/issue/1197/docs/5.0/components/forms/

### CODE REVIEW

**Review by mmunro-ltrr — DISMISSED** [review]

**Review by joeparsons — DISMISSED** [review]

**Comment by joshuasosa** [comment]
Should `.col-form-label`, `.col-form-label-sm`, and `.col-form-label-lg` get bolds? For example, "[Radios](https://review.digital.arizona.edu/arizona-bootstrap/issue/1197/docs/5.0/components/forms/#horizontal-form)" is not bolded here. ("Checkbox" doesn't have col-form-label and wouldn't get bold in this example, though maybe it should get the class.)

**Review by mmunro-ltrr — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Comment by joeparsons** [comment]
> Should `.col-form-label`, `.col-form-label-sm`, and `.col-form-label-lg` get bolds? For example, "[Radios](https://review.digital.arizona.edu/arizona-bootstrap/issue/1197/docs/5.0/components/forms/#horizontal-form)" is not bolded here. ("Checkbox" doesn't have col-form-label and wouldn't get bold in this example, though maybe it should get the class.)

We discussed this in our 2024-07-26 Friday meeting and we think this was intentional / by design.  The Bootstrap 5 docs included in Arizona Bootstrap still need a lot of work so we're not sure about that but we can take a closer look in the follow-up backport to 2.x PR.

**Comment by danahertzberg** [comment]
@danahertzberg Will look into the visual discrepancy here. https://review.digital.arizona.edu/arizona-bootstrap/issue/1197/docs/5.0/components/forms/#horizontal-form

**Comment by danahertzberg** [comment]
@akslay will make these changes before Friday's meeting [per Slack](https://uarizona.slack.com/archives/CLWJM4JH2/p1722028419890519?thread_ts=1722023091.373469&cid=CLWJM4JH2).

**Comment by mmunro-ltrr** [comment]
I'm finding some linting errors on a local build, too, so will be committing a further change....

**Review by mmunro-ltrr — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Pull request merged**
