### PR TITLE
Display Microsoft Edge on Mac as Supported

### PR DESCRIPTION
**Pull request by its-me-mario**
Microsoft released the Chromium-based Edge in early 2020.

It seems like this should be supported, but I would differ to your team to have the final say.

[Issue 226](https://github.com/az-digital/arizona-bootstrap/issues/226)

### CODE REVIEW

**Comment by mmunro-ltrr** [comment]
It looks like the file is based on one from upstream Twitter Bootstrap, and this copy hasn't been changed since first customized for Arizona Bootstrap a year or two ago. There are several more changes in the one from the last release of Twitter Bootstrap v4
https://raw.githubusercontent.com/twbs/bootstrap/v4.6.0/site/content/docs/4.6/getting-started/browsers-devices.md
though even this itself has some stale information (it references a page devoted to browser bugs, now deprecated in Twitter Bootstrap). The `site/docs` subdirectory is about to become `site/content/docs` so it might be best to defer updating the browser compatibility list until after the change.

**Comment by its-me-mario** [comment]
Seems reasonable to wait until after the `site/content/docs` change.

**Comment by camikazegreen** [comment]
Are we planning on merging this or closing it?

**Comment by mmunro-ltrr** [comment]
> Are we planning on merging this or closing it?

It's effectively blocked by PR #233 (which will move directories around).

**Review by mmunro-ltrr — APPROVED** [review]
Should be ok with the restructured directory trees for the docs now.

**Review by joeparsons — APPROVED** [review]

**Pull request merged**
