### PR TITLE
Closes #441, Closes #479: Add a RELEASES.md document.

### LINKED ISSUE #441: Add Bootstrap releases document
## Motivation
I want a definition for semantic releases on Arizona Bootstrap

## Proposed Resolution
Add new releases doc to bootstrap repo with definitions (potentially similar to quickstart)

### LINKED ISSUE #479: Document how to create a release
For creating release notes: `git log v2.0.13..HEAD --pretty='format:- %s'`
Basically just need to run this action https://github.com/az-digital/arizona-bootstrap/actions/workflows/release.yml

Leave off the v

### PR DESCRIPTION
**Pull request by mmunro-ltrr**

### CODE REVIEW

**Review by akslay — APPROVED** [review]

**Comment by trackleft** [comment]
Woah, thanks @mmunro-ltrr

**Review by jwmoore1 — APPROVED** [review]

**Review by joeparsons — COMMENTED** [review]
This looks great to me.  Thanks @mmunro-ltrr.  Do you think we'll need to consider adding additional release branches similar to what we're doing in Quickstart so that we can start following this and creating minor releases?

**Review by joeparsons — APPROVED** [review]
I absolutely agree with this as a new policy for Arizona Bootstrap releases though we'll probably need additional issues/PRs to start implementing this policy.

**Comment by mmunro-ltrr** [comment]
@joeparsons: I think we'll have to revise this document and restructure things a bit the first time there's a major bugfix or security remediation that we need to backport to previous minor releases.

**Comment by trackleft** [comment]
How do we want to handle CDN assets, do we want to add minor release buckets?

2.1.x-latest
2.2.x-latest

**Comment by mmunro-ltrr** [comment]
@trackleft: they're all just names within one S3 bucket, so it should be easy to change. I'll look at what is involved (it diverged a little from what we were doing with the old UA Bootstrap).

**Review by trackleft — APPROVED** [review]

**Pull request merged**
