### PR TITLE
(HOLD) WIP | Add clickable card styles and docs

### LINKED ISSUE #353: Add hover states for all cards (clickable cards)
## Motivation
We will be adding "clickable card" functionality to Arizona Quickstart 2.0 (https://github.com/az-digital/az_quickstart/issues/737). This means that each style of card needs a hover state. 

## Proposed Resolution

- [x] For standard cards with background colors, leverage the built-in SCSS `darken()` function, which will darken the given background-color.
- [x] For Landing Grid cards, match the mockup from az-digital/az_quickstart#982
- [x] For all card types, add the visual indicator arrow to the card
- [x] For all card types, update/add documentation pertaining to "clickable cards"
        - The documentation for [Borderless Cards](https://digital.arizona.edu/arizona-bootstrap/docs/2.0/components/card/#borderless) is no longer accurate as of AZQS 2.0
        - Add a "Clickable Card" section to each card style (background and color, border, borderless, landing grid)
- [x] Utilize the Stretched Link utility class

## Relevant Screenshots

https://user-images.githubusercontent.com/52931751/131753327-9b6c9b73-ce4c-4712-8b47-35788a248fc0.mov

### PR DESCRIPTION
**Pull request by akslay**
~~This PR is a work in progress and is currently being reviewed by the DRC.~~

Closes #353

### CODE REVIEW

**Comment by mmunro-ltrr** [comment]
Tested locally both in this branch, and after merging it into the PR #358 changes: in both cases the documentation site built, and passed the lint checks.

**Comment by akslay** [comment]
**Feedback from Barbie on 2021/09/22:**
__________________________________

Hi Ashley,
Thanks so much for taking the time to create an example. Wow – I listened to these examples with JAWS and Chrome, and I am impressed with the look and feel of the cards. I like that the arrows highlight that it’s all a section for navigation – however I did notice a variation on what was announced depending on how I navigate through the cards. Here’s what the screen reader announced when I used the arrow keys to go through the cards section, (I removed all the text from the card description to save you from reading it all):
 
“heading level 3‑ Main Library
The go-to place to study, create, collaborate, and get things done…
Link‑ Visit the Main Library’s website”

“heading level 3‑ Health Sciences Library
The primary source of knowledge-based health information in Arizona…
Link‑ Visit Health Sciences library’s website”

“heading level 3‑ Fine Arts Library
A north-campus haven for students and faculty…
Link‑ Visit the Fine Arts library’s website”
 
Here’s what the screen reader announced when I only use Tab to navigate:
“Visit the Main Library’s Website Link - Visit the Main Library’s Website”
“Visit Health Sciences library’s website Link‑“ 
“Visit the Fine Arts library’s website Link‑“
 
The difference with the first card – is that what you were mentioning about using the title tag and the aria label?
 
Let me know!
 
Thanks,
Barbie

**Comment by akslay** [comment]
**Feedback from Dawn on 2021/09/22:**
__________________________________

Hi Ashley,
 
This is looking great! The experience that Barbie saw with the difference between using our arrow keys to navigate vs the tab key is expected. The tab key really serves as an option to get directly to the links where as the arrow keys act like they do for us when we’re slowly scrolling down a page, just using our arrow keys instead of the scroll button on the mouse.
 
For the ARIA label vs Title tag – it looks like having both is a good option with ARIA Label prioritized over title. See https://www.deque.com/blog/text-links-practices-screen-readers/ and I also found this https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA8.html - do those help with what you are looking at?
 
Bear Down,
Dawn

**Comment by akslay** [comment]
**2021/09/29 workshop discussion decision:**

- Hold off for now. More discussion required.

**Comment by joeparsons** [comment]
We're going to close this for now. If more clickable card options are needed we can definitely re-open.

**Pull request closed without merging**
