### PR TITLE
0.0.3

### PR DESCRIPTION
**Pull request by kevcooper**
This is a test of the new release process

### CODE REVIEW

**Comment by joeparsons** [comment]
Shouldn't the `dist` directory also be updated?

**Comment by kevcooper** [comment]
If i run `npm run dist` there are no changes to the dist directory. If I first delete `dist` before running `npm run dist`, I get a bunch of npm errors related to being unable to move non-existant directories.

Should there currently be changes that show up in dist?

**Comment by joeparsons** [comment]
Maybe not.  I suppose `dist` may have already been (manually) updated recently enough.

**Comment by kevcooper** [comment]
there are some new files that get created if I delete `dist` first though

**Comment by kevcooper** [comment]
never mind, they're not really new they just have the wrong name and are in the wrong location

**Pull request merged**
