### PR TITLE
Update light gray text-muted colors to pass WCAG 2.0 AAA accessibility standards.

### PR DESCRIPTION
**Pull request by trackleft**

### CODE REVIEW

**Comment by trackleft** [comment]
Problem with Sass that says the commented out variables do not exist, which is why they are commented out.

**Review by joeparsons — APPROVED** [review]

**Comment by trackleft** [comment]
Before: 
https://digital.arizona.edu/arizona-bootstrap/docs/2.0/utilities/colors/
https://digital.arizona.edu/arizona-bootstrap/docs/2.0/components/navs/#available-styles
https://digital.arizona.edu/arizona-bootstrap/docs/2.0/components/dropdowns/#disabled

After: 
https://review.digital.arizona.edu/arizona-bootstrap/user-story/166-change-text-muted-color-to-pass-wcag-aaa/docs/2.0/utilities/colors/
https://review.digital.arizona.edu/arizona-bootstrap/user-story/166-change-text-muted-color-to-pass-wcag-aaa/docs/2.0/components/navs/#available-styles
https://review.digital.arizona.edu/arizona-bootstrap/user-story/166-change-text-muted-color-to-pass-wcag-aaa/docs/2.0/components/dropdowns/#disabled

**Comment by smayden** [comment]
This looks good. I noticed the text example on this page that uses the muted gray has poor color contrast:

https://review.digital.arizona.edu/arizona-bootstrap/user-story/166-change-text-muted-color-to-pass-wcag-aaa/docs/2.0/components/dropdowns/#disabled

text example

**Comment by trackleft** [comment]
> This looks good. I noticed the text example on this page that uses the muted gray has poor color contrast:
> 
> https://review.digital.arizona.edu/arizona-bootstrap/user-story/166-change-text-muted-color-to-pass-wcag-aaa/docs/2.0/components/dropdowns/#disabled
> 
> text example

Should we just do light gray for this or just do white?  White might look like a link, which is why I think it was gray in the first place.

**Comment by trackleft** [comment]
Changed dropdown text color to cool gray.

**Comment by trackleft** [comment]
[ ] Verify that dubbot issue marks this as resolved.

**Review by mmunro-ltrr — APPROVED** [review]

**Review by mmunro-ltrr — APPROVED** [review]

**Comment by trackleft** [comment]
Review site seems to work fine after fixing merge conflicts
 https://review.digital.arizona.edu/arizona-bootstrap/user-story/166-change-text-muted-color-to-pass-wcag-aaa/

**Review by joeparsons — APPROVED** [review]

**Pull request merged**
