### PR TITLE
Use an ephemeral local Docker image preconfigured with npm — Closes #70

### LINKED ISSUE #70: User Management

### PR DESCRIPTION
**Pull request by mmunro-ltrr**

### CODE REVIEW

**Comment by mmunro-ltrr** [comment]
The` _site` subdirectory should be locked up inside the container for local development, but the S3 upload from the GitHub Actions needs to get at it: looking at copying it conditionally.

**Comment by joeparsons** [comment]
@mmunro-ltrr Is this for issue #73?  I can't seem to find an issue #70 (for connecting with ZenHub)

**Comment by mmunro-ltrr** [comment]
> @mmunro-ltrr Is this for issue #73? I can't seem to find an issue #70 (for connecting with ZenHub)
Yes, it's for Issue #73 (don't know how I arrived at that other number), To make matters worse, I called the branch feature/70. I might just decline this one & re-do it properly: the other required change is going back to `arizona-bootstrap` in the review URLs, and I should add more documentation.

**Comment by mmunro-ltrr** [comment]
This pull request and associated branch didn't reference the correct issue number.

**Pull request closed without merging**
